# Generated by Django 4.1.7 on 2023-03-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_gate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
