# Generated by Django 4.1.7 on 2023-03-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_gate', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
