# Generated by Django 4.1.7 on 2023-04-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_gate', '0013_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
