# Generated by Django 4.1.7 on 2023-04-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_gate', '0014_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
