# Generated by Django 4.2.3 on 2023-08-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_gate', '0015_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
