# Generated by Django 4.2.3 on 2023-08-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_gate', '0018_remove_feedback_sname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
