# Generated by Django 4.2.3 on 2023-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_gate', '0021_alter_feedback_email_alter_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
