# Generated by Django 4.2.3 on 2023-08-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_gate', '0022_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
