# Generated by Django 4.2.3 on 2023-09-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_gate', '0023_feedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='rating',
            new_name='rate',
        ),
    ]
